# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnsconfig',
            old_name='ip_text',
            new_name='left_text',
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='left_next_hop',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='left_source_ip',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='left_subnet_text',
            field=models.CharField(default='', max_length=19),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='right_next_hop',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='right_source_ip',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='right_text',
            field=models.CharField(default='', max_length=16),
        ),
    ]
