# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0003_dnsconfig_right_subnet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_text',
            field=models.CharField(default='', max_length=16),
        ),
    ]
