# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0004_auto_20180527_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsconfig',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='keyring_tries',
            field=models.CharField(default='%forever', max_length=16),
        ),
    ]
