# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0006_auto_20180528_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank, Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='keyring_tries',
            field=models.CharField(default='%forever', help_text='Choice - %forever', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_next_hop',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_source_ip',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_subnet_text',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_text',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_next_hop',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_source_ip',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_subnet_text',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_text',
            field=models.CharField(default='', help_text='Choices - %defaultroute OR leave blank', max_length=16),
        ),
    ]
