# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0007_auto_20180529_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsconfig',
            name='left_subnet_text',
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='connaddrfamily',
            field=models.CharField(default='ipv4', help_text='Valid/accepted values are ipv4 OR ipv6', max_length=4),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='keyexchange',
            field=models.CharField(default='ike', help_text='The default and currently the only accepted value is ike', max_length=3),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftaddresspool',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftprotoport',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftsubnet',
            field=models.CharField(default='', help_text='eg. vhost:%no,%priv', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftsubnets',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftupdown',
            field=models.CharField(default='', help_text='eg. ipsec _updown --route yes OR %disabled', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftvti',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='rightaddresspool',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='type',
            field=models.CharField(default='tunnel', help_text='Valid - tunnel OR transport OR passthrough OR drop OR reject', max_length=12),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(default='', help_text='See Reference - https://libreswan.org/man/ipsec.conf.5.html', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='keyring_tries',
            field=models.CharField(default='%forever', help_text='Valid - Input OR %forever', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_next_hop',
            field=models.CharField(default='', help_text='Valid - %defaultroute OR %direct OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_source_ip',
            field=models.CharField(default='', help_text='Valid - Input IP OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_text',
            field=models.CharField(default='', help_text='Valid - Input IP OR %defaultroute OR %any OR %opportunistic', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_next_hop',
            field=models.CharField(default='', help_text='Valid - Input IP OR %defaultroute OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_source_ip',
            field=models.CharField(default='', help_text='Valid - Input IP OR leave blank', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_subnet_text',
            field=models.CharField(default='', help_text='Valid - Input IP OR leave blank', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_text',
            field=models.CharField(default='', help_text='Valid - Input IP OR %defaultroute OR %any (for remote end only)', max_length=16),
        ),
    ]
