# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0010_auto_20180530_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vpnforremotehost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_name', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=20)),
                ('keyexchange', models.CharField(default='ike', help_text='The default and currently the only accepted value is <b><a>ike</a></b>', max_length=3)),
                ('connaddrfamily', models.CharField(default='ipv4', help_text='Valid/accepted values are <b><a>ipv4</a></b> OR <b><a>ipv6</a></b>', max_length=4)),
                ('type', models.CharField(default='tunnel', help_text='Valid - <b><a>tunnel</a></b> OR <b><a>transport</a></b> OR <b><a>passthrough</a></b> OR <b><a>drop</a></b> OR <b><a>reject</a></b>', max_length=12)),
                ('left', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b> OR <b><a>%opportunistic</a></b>', max_length=16)),
                ('leftsubnet', models.CharField(blank=True, default='', help_text='eg. vhost:%no,%priv', max_length=16)),
                ('leftsubnets', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16)),
                ('leftvti', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16)),
                ('leftaddresspool', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16)),
                ('leftprotoport', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16)),
                ('leftnexthop', models.CharField(blank=True, default='', help_text='Valid - <b><a>%defaultroute</a></b> OR <b><a>%direct</a></b> OR <b><a>leave blank</a></b>', max_length=16)),
                ('leftsourceip', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16)),
                ('leftupdown', models.CharField(blank=True, default='', help_text='eg. <b><a>ipsec _updown --route yes</a></b> OR <b><a>%disabled</a></b>', max_length=16)),
                ('right', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b>', max_length=16)),
                ('rightsubnet', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=19)),
                ('rightaddresspool', models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16)),
                ('rightnexthop', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>leave blank</a></b>', max_length=16)),
                ('rightsourceip', models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16)),
                ('keyringtries', models.CharField(default='%forever', help_text='eg. <b><a>%forever</a></b>', max_length=16)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.RenameModel(
            old_name='dnsconfig',
            new_name='subnettosubnet',
        ),
    ]
