# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0011_auto_20180530_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='keyexchange',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftaddresspool',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftnexthop',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftprotoport',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftsourceip',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftsubnets',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftupdown',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='leftvti',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='rightaddresspool',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='rightnexthop',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='rightsourceip',
        ),
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='type',
        ),
        migrations.AddField(
            model_name='subnettosubnet',
            name='also',
            field=models.CharField(blank=True, default='', help_text='The value is a section <b><a>name</a></b>', max_length=20),
        ),
        migrations.AddField(
            model_name='subnettosubnet',
            name='auto',
            field=models.CharField(blank=True, default='', help_text='eg. <b><a>start</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='subnettosubnet',
            name='connaddrfamily',
            field=models.CharField(blank=True, default='ipv4', help_text='Valid/accepted values are <b><a>ipv4</a></b> OR <b><a>ipv6</a></b>', max_length=4),
        ),
        migrations.AlterField(
            model_name='subnettosubnet',
            name='connection_name',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=20),
        ),
        migrations.AlterField(
            model_name='subnettosubnet',
            name='keyringtries',
            field=models.CharField(blank=True, default='%forever', help_text='eg. <b><a>%forever</a></b>', max_length=16),
        ),
    ]
