# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0015_auto_20180603_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='token',
            field=models.CharField(default='oglyekkhi6nh1ejzju02', max_length=20),
        ),
    ]
