# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0019_auto_20180607_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatecertificate',
            name='key_name',
            field=models.CharField(blank=True, default='', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=15),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='token',
            field=models.CharField(default='93019qqfsaithohxdm23', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
    ]
