# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0021_auto_20180612_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecertificate',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Valid - <b><a>True</a></b> OR <b><a>False</a></b>'),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='token',
            field=models.CharField(default='kd0zqq8ju2d3q0bvs1m1', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
        migrations.AlterField(
            model_name='vpnforremotehost',
            name='mobike',
            field=models.CharField(blank=True, default='no', help_text='Valid - <b><a>no</a></b> OR <b><a>yes</a></b>', max_length=3),
        ),
    ]
