# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0022_auto_20180620_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatecertificate',
            name='token',
            field=models.CharField(default='gl0aof86f442k1l25g07', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
    ]
