# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0023_auto_20180620_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatecertificate',
            name='token',
        ),
    ]
