# Generated by Django 2.0.6 on 2018-06-29 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0027_auto_20180629_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateconfiguration',
            name='expiration_period',
            field=models.PositiveIntegerField(default='365', help_text='Certificate Expiration period in days, value <= 9999', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
