# Generated by Django 2.0.6 on 2018-06-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0028_auto_20180629_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateconfiguration',
            name='common_name',
            field=models.CharField(default='user', help_text="Enter Common Name (eg, your name or your server's hostname), user will write the username of user.", max_length=20),
        ),
        migrations.AlterField(
            model_name='certificateconfiguration',
            name='email_address',
            field=models.CharField(default='@email.com', help_text='It will be shown as username@email.com, if common name is user. else it will be shown as @email.com', max_length=30),
        ),
    ]
