# Generated by Django 2.0.6 on 2018-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0029_auto_20180629_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateRootCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_password', models.CharField(blank=True, default='', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20)),
            ],
        ),
    ]
