# Generated by Django 2.0.6 on 2018-06-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0030_generaterootca'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateRootCA',
            new_name='GenerateRootCertificate',
        ),
    ]
