# Generated by Django 2.0.6 on 2018-07-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0033_auto_20180703_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateRootCertificate',
            new_name='GeneratePrivateKey',
        ),
    ]
