# Generated by Django 2.0.6 on 2018-07-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0034_auto_20180703_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generateprivatekey',
            old_name='cert_name',
            new_name='key_name',
        ),
        migrations.RenameField(
            model_name='generateprivatekey',
            old_name='cert_password',
            new_name='key_password',
        ),
    ]
