# Generated by Django 2.0.6 on 2018-07-03 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0035_auto_20180703_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateRootCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='CA', help_text='Enter 2 Letter country code', max_length=2)),
                ('state_province', models.CharField(default='Ontario', help_text='Enter State or Province Name (full name)', max_length=20)),
                ('locality_name', models.CharField(default='Ottawa', help_text='Enter Locality name (eg.city)', max_length=20)),
                ('organization_name', models.CharField(default='No Hats Corporation', help_text='Enter Organization name (eg. company ltd)', max_length=30)),
                ('organization_unit', models.CharField(default='Clients', help_text='Enter Organization unit name (eg. section name)', max_length=20)),
                ('common_name', models.CharField(default='user', help_text="Enter Common Name (eg, your name or your server's hostname).", max_length=20)),
                ('email_address', models.CharField(default='@email.com', help_text='Enter email address', max_length=30)),
                ('expiration_period', models.PositiveIntegerField(default='365', help_text='Certificate Expiration period in days, value <= 9999', validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.AlterField(
            model_name='generateprivatekey',
            name='key_name',
            field=models.CharField(default='ca.key.pem', help_text='Key identification name', max_length=20),
        ),
    ]
