# Generated by Django 2.0.6 on 2018-07-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0036_auto_20180703_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaterootcertificate',
            name='password',
            field=models.CharField(default='gxpu08tkkmvhs1vm3gi88tkkmvhs1', help_text='Please set a strong password.', max_length=30),
        ),
    ]
