# Generated by Django 2.0.6 on 2018-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0037_generaterootcertificate_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaterootcertificate',
            name='password',
            field=models.CharField(default='gxpu08tkkmvhs1vm3gi88tkkmvhs1', help_text='Enter the Private key password.', max_length=30),
        ),
    ]
