# Generated by Django 2.0.6 on 2018-07-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0038_auto_20180703_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestSavedKeyPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_password', models.CharField(blank=True, default='', help_text='<b><a>System Generated, Do Not Alter</a></b>', max_length=20)),
            ],
        ),
    ]
