# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0039_latestsavedkeypassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsavedkeypassword',
            name='key_password',
            field=models.CharField(blank=True, default='asdfjkl', help_text='<b><a>System Generated, Do Not Alter</a></b>', max_length=20),
        ),
    ]
