# Generated by Django 2.0.6 on 2018-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0040_auto_20180709_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestSavedKeyPassword',
        ),
    ]
