# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0041_delete_latestsavedkeypassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaterootcertificate',
            name=b'password',
        ),
    ]
