# Generated by Django 2.0.6 on 2018-07-22 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0042_remove_generaterootcertificate_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKeyPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(default='Private Key', max_length=20)),
                ('priv_key_password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='generaterootcertificate',
            name='common_name',
            field=models.CharField(default='Libreswan.org', help_text="Enter Common Name (eg, your name or your server's hostname).", max_length=20),
        ),
        migrations.AlterField(
            model_name='generaterootcertificate',
            name='email_address',
            field=models.CharField(default='support@libreswan.org', help_text='Enter email address', max_length=30),
        ),
        migrations.AlterField(
            model_name='generaterootcertificate',
            name='expiration_period',
            field=models.PositiveIntegerField(default='665', help_text='Certificate Expiration period in days, value <= 9999', validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
