# Generated by Django 2.0.6 on 2018-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0043_auto_20180722_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekeypassword',
            name='id',
        ),
        migrations.AlterField(
            model_name='privatekeypassword',
            name='key_name',
            field=models.CharField(default='Private Key', max_length=20, primary_key=True, serialize=False),
        ),
    ]
