# Generated by Django 2.0.6 on 2018-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0045_generatecertificate_cert_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificateconfiguration',
            options={'verbose_name': '3. User Certificate configuration options', 'verbose_name_plural': '3. User Certificate configuration options'},
        ),
        migrations.AlterModelOptions(
            name='generatecertificate',
            options={'verbose_name': '4. Generate OR Revoke User Certificate', 'verbose_name_plural': '4. Generate OR Revoke User Certificates'},
        ),
        migrations.AlterModelOptions(
            name='generateprivatekey',
            options={'verbose_name': '1. Generate CA Private Key', 'verbose_name_plural': '1. Generate CA Private Key'},
        ),
        migrations.AlterModelOptions(
            name='generaterootcertificate',
            options={'verbose_name': '2. Generate CA Root Certificate', 'verbose_name_plural': '2. Generate CA Root Certificate'},
        ),
        migrations.AlterModelOptions(
            name='subnettosubnet',
            options={'verbose_name': '02. Subnet to Subnet Conection', 'verbose_name_plural': '02. Subnet to Subnet Connections'},
        ),
        migrations.AlterModelOptions(
            name='vpnforremotehost',
            options={'verbose_name': '01. VPN for Remote Host', 'verbose_name_plural': '01. VPN for Remote Hosts'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificate_revoked',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='cert_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='<b><a>System Generated - Do not alter</a></b>', max_length=15),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='cert_password',
            field=models.CharField(blank=True, default='', editable=False, help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='key_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='<b><a>System Generated - Do not alter</a></b>', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, editable=False, help_text='Valid - <b><a>True</a></b> OR <b><a>False</a></b>'),
        ),
    ]
