# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dnsconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_text', models.CharField(max_length=16)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
