# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_auto_20180525_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsconfig',
            name='right_subnet_text',
            field=models.CharField(default='', max_length=19),
        ),
    ]
