# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0005_auto_20180527_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='keyring_tries',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='%forever', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_next_hop',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_source_ip',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_subnet_text',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left_text',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_next_hop',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_source_ip',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_subnet_text',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right_text',
            field=models.CharField(choices=[('%defaultroute', '%defaultroute'), ('', 'blank-default')], default='', max_length=16),
        ),
    ]
