# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0008_auto_20180530_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsconfig',
            name='keyring_tries',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='left_next_hop',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='left_source_ip',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='left_text',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='right_next_hop',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='right_source_ip',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='right_subnet_text',
        ),
        migrations.RemoveField(
            model_name='dnsconfig',
            name='right_text',
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='keyringtries',
            field=models.CharField(default='%forever', help_text='eg. <b><a>%forever</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='left',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b> OR <b><a>%opportunistic</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftnexthop',
            field=models.CharField(default='', help_text='Valid - <b><a>%defaultroute</a></b> OR <b><a>%direct</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='leftsourceip',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='right',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='rightnexthop',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='rightsourceip',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AddField(
            model_name='dnsconfig',
            name='rightsubnet',
            field=models.CharField(default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=19),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='connaddrfamily',
            field=models.CharField(default='ipv4', help_text='Valid/accepted values are <b><a>ipv4</a></b> OR <b><a>ipv6</a></b>', max_length=4),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='keyexchange',
            field=models.CharField(default='ike', help_text='The default and currently the only accepted value is <b><a>ike</a></b>', max_length=3),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftaddresspool',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftprotoport',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftsubnets',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftupdown',
            field=models.CharField(default='', help_text='eg. <b><a>ipsec _updown --route yes</a></b> OR <b><a>%disabled</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftvti',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='rightaddresspool',
            field=models.CharField(default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='type',
            field=models.CharField(default='tunnel', help_text='Valid - <b><a>tunnel</a></b> OR <b><a>transport</a></b> OR <b><a>passthrough</a></b> OR <b><a>drop</a></b> OR <b><a>reject</a></b>', max_length=12),
        ),
    ]
