# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0009_auto_20180530_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnsconfig',
            name='connection_name',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=20),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='left',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b> OR <b><a>%opportunistic</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftaddresspool',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftnexthop',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>%defaultroute</a></b> OR <b><a>%direct</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftprotoport',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftsourceip',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftsubnet',
            field=models.CharField(blank=True, default='', help_text='eg. vhost:%no,%priv', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftsubnets',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftupdown',
            field=models.CharField(blank=True, default='', help_text='eg. <b><a>ipsec _updown --route yes</a></b> OR <b><a>%disabled</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='leftvti',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='right',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>%any</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='rightaddresspool',
            field=models.CharField(blank=True, default='', help_text='See Reference - <a>https://libreswan.org/man/ipsec.conf.5.html</a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='rightnexthop',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>%defaultroute</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='rightsourceip',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=16),
        ),
        migrations.AlterField(
            model_name='dnsconfig',
            name='rightsubnet',
            field=models.CharField(blank=True, default='', help_text='Valid - <b><a>Input IP</a></b> OR <b><a>leave blank</a></b>', max_length=19),
        ),
    ]
