# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0018_auto_20180604_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnettosubnet',
            name='connaddrfamily',
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='cert_password',
            field=models.CharField(blank=True, default='', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='email_verified',
            field=models.CharField(default=False, help_text='Valid - <b><a>True</a></b> OR <b><a>False</a></b>', max_length=5),
        ),
        migrations.AlterField(
            model_name='generatecertificate',
            name='token',
            field=models.CharField(default='pq2wrg92lr85ochj6aqf', help_text='<b><a>System Generated - Do not alter</a></b>', max_length=20),
        ),
    ]
